### ISSUE TITLE
Plugin don't fired on events

### ISSUE THREAD

**Issue by fabricemoreau** [allonzy/artillery-plugin-json-include#1]
Hi,

I tried to use the plugin from Docker image which contains Artillery 2.0.0-27, the plugin is loaded, but the events are ignored.

My Artillery yaml:
```yaml
config:
  plugins:
    json-include: {}
  target: "http://myurl"
  phases:
    - duration: 10
      arrivalRate: 10
      name: Warm up
    - duration: 20
      arrivalRate: 5
      rampTo: 20
      name: Ramp up to load
    - duration: 30
      arrivalRate: 20
      name: Sustained load
scenarios:
  - name: "Création, visualisation, liste, suppression"
    flow: 
      - post:
          url: "/plots"
          json: "!include(plot.json)"
```

the payload received by my api is "!include(plot.json)" in place of the plot.json content. 

Here is the command I run to start a container:

```bash
docker run --entrypoint=sh -it --rm -v $pwd:/usr/src/app -w /usr/src/app artilleryio/artillery:2.0.0-23
```
I also tried lastest version.

Inside the container, I run these commands:
```bash
cd /home/node/artillery
npm install artillery-plugin-json-include
cd /usr/src/app
# the artillery command inside the container is named `run`
run run performance.yml
```

If I modify the plugin to remove the line
```
events.on('phaseStarted', function() {
```
, the json file is correctly loaded and the tests executes as expected.

Maybe the problem is in Artillery code.
