### ISSUE TITLE
The JSON file contents should get included when using a loop in a flow of a scenario

### ISSUE THREAD

**Issue by Paul-Pladijs** [allonzy/artillery-plugin-json-include#3]
The JSON contents does not get included when using a **loop** construct in a flow, example code:

```
config:
  target: http://targetmachine.com
  plugins:
    json-include: {}
scenarios:
  - flow:
      - loop:
          - post:
              url: "/route"
              json: "!include(relativePath.json)"
        count: 1
```
As soon you remove the `loop` level, it works.

UPDATE: the same issue for a `parallel` item. Note that this construct is technically undocumented, however it can be used. [See here for more info about that](https://github.com/artilleryio/artillery-core/pull/210).

Example with a **parallel** construct:
```
config:
  target: http://targetmachine.com
  plugins:
    json-include: {}
scenarios:
  - flow:
      - parallel:
          - post:
              url: "/route1"
              json: "!include(relativePath.json)"
          - post:
              url: "/route2"
              json: "!include(relativePath.json)"
```
